### ISSUE TITLE
Branches

### ISSUE THREAD

**Issue by loubi72** [loubi72/HuffCode#2]
War nicht der Sinn der Sache hinter den Branches, dass man erstmal die Pull Request stellt, damit jmd anderer nochmal rüberguckt, ob die Änderungen gut sind?

**Comment by Zwelf** [comment]
Ja, hab war nicht so gewollt, hab versucht meinen pull request zu beantworten, den ich aus versehen in meiner branch gemacht hab und danach hab ich feststellt, dass es in deinem repository war ^^.
Eigentlich kann jeder das Repository forken und dann von außen die Pull-request machen.

**Comment by loubi72** [comment]
Stimmt, auch nicht schlecht
